apiVersion: v1
kind: Service
metadata:
  name: opec-proxy
spec:
  type: NodePort
  selector:
    app: opec-proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32280
